server:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:course
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enable: true
      path: /h2-console

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
